public enum BattleTurnPhase
{
    PLAYER_TURN_START,
    PLAYER_ACTION_SELECTION,
    PLAYER_ACTION_ATTACKING,
    PLAYER_ACTION_FLEEING,
    ENEMY_TURN,
    PROCESSING_PLAYER_DAMAGE,
    PROCESSING_ENEMY_DAMAGE,
    BATTLE_OVER_LOSE,
    BATTLE_OVER_WIN
}